### ISSUE TITLE
nav: Link to RPC folder

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft-docs#22]
We need a link somewhere in the nav (possibly right at the bottom of the nav?) to the OpenAPI docs in the `/${VERSION}/rpc/` folder.

This folder is already created when fetching the releases' documentation here: https://github.com/cometbft/cometbft-docs/blob/7e198ef121cfa594ce5c4f4fa2f9f571511dc8be/Makefile#L22

**Comment by aaronmw** [comment]
This can be done by renaming `rpc/index.html` to `rpc/rpc.html` (or something else) and then adding this `rpc/index.md`:

```
---
order: 5
parent:
  title: RPC
  order: 5
---

# RPC

Link to RPC: [RPC Page](./rpc.html)
```

Results in:

![image](https://user-images.githubusercontent.com/1236267/220678203-93cee0cd-2307-4ac8-9232-0555910049f6.png)
