### ISSUE TITLE
Version selector overlap

### ISSUE THREAD

**Issue by andynog** [cometbft/cometbft-docs#24]
Noticed that when selecting the `v0.37-rc2` version on the version selector dropdown, the version text overlaps with the down arrow

![version_selector](https://user-images.githubusercontent.com/45477427/217602779-e8215bff-1553-4802-8e80-be8025e459fe.png)

Browser: Firefox
OS: Ubuntu

**Comment by andynog** [comment]
Noticed this on Firefox (Linux Fedora)

**Comment by aaronmw** [comment]
This got fixed somewhere along the way.
