### ISSUE TITLE
Documents are hard to read on widescreen monitors

### ISSUE THREAD

**Issue by lasarojc** [cometbft/cometbft-docs#48]
When reading the documentation on a wide screen, the glow on the right sight becomes really bright and makes it hard to read, as seen in the attached image.

![image](https://user-images.githubusercontent.com/2686194/221251182-6fd98db4-8475-434d-b01a-adbaf43730a6.png)

Could a more friendly schema be used?

**Comment by andynog** [comment]
I second that. On my monitor the glow goes over the center text and it's hard to read sometimes. I'd rather have the glow contained just to the end of right corner not overlaying over the main text if possible. Or completely remove it if that makes it easier to read.
