### ISSUE TITLE
Certain relative links not rendering correctly

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft-docs#7]
Even though the `jekyll-relative-links` plugin is enabled (for pages and collections), it appears as though it's not working in some cases.

When landing on the home page, for example, the link to the "quick start" page attempts to direct you to `/v0.34/introduction/quick-start.md` instead of `/v0.34/introduction/quick-start/` (the latter being the correct one). But the menu renders this particular link correctly.

[Screencast from 2023-01-28 04:27:39 PM.webm](https://user-images.githubusercontent.com/212999/215292072-6d19eb76-2894-4e41-a207-f6924a6c677f.webm)

**Comment by andynog** [comment]
I believe these links are rendering fine now either online on local builds. There are still several broken links but those will be fixed in this [issue](https://github.com/cometbft/cometbft/issues/319). The broken links check were implemente in #25 

So I believe this issue might be closed.
